    av=V(5);
    for(a=0;a<5;a++)in>>av[a];
    while(av!=V({1,2,3,4,5})){
        for(a=0;a<4;a++){
            if(av[a]>av[a+1]){
                swap(av[a],av[a+1]);
                outv(av);
            }
        }
    }