    in>>a>>b;
    av=V(a);
    for(c=0;c<b;c++){
        in>>d;
        av[d-1]=1;
    }
    c=0;
    al=L(a)+L(a)*L(a-1)/2;
    for(d=0;d<a;d++){
        if(av[d]==0)c++;
        else{
            al-=L(c);
            al-=L(c)*L(c-1)/2;
            c=0;
        }
    }
    al-=L(c);
    al-=L(c)*L(c-1)/2;
    out<<al<<nl;