    in>>a;
    while(a!=0){
        bd=0;
        avd.clear();
        for(b=0;b<a;b++){
            in>>ad;
            avd.add(ad);
            bd+=ad;
        }
        cd=bd/b;
        dd=D(I(cd*100))/100;
        ed=dd+0.01;
        fd=0;
        gd=0;
        for(b=0;b<a;b++){
            if(avd[b]<cd){
                fd+=dd-avd[b];
                gd+=dd;
            }
            else{
                fd+=avd[b]-ed;
                gd+=ed;
            }
        }
        out<<"$"<<setprecision(2)<<fixed<<(fd+abs(gd-bd))/2<<nl;
        in>>a;
    }